spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':  #匹配所有请求
             allowedOrigins: "*" #跨域处理 允许所有的域
             allowedMethods:  #支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          - id: goods_route   # 唯一标识符
##        uri: http://localhost:18081
            uri: lb://goods
            predicates:
            - Path=api/brand/**
#           - Path=/api/brand/**
            filters:
#        路径前添加一个路径如：/brand
#            - PrefixPath=/brand
##        将路径中第一个路径去掉
              - StripPrefix=1
#            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的factory
#              args:
#                # 用户身份唯一标识符
#                key-resolver: "#{@ipKeyResolver}"
#                # 允许用户每秒执行多少请求，而不会丢弃任何请求。这是令牌桶填充的速率
#                redis-rate-limiter.replenishRate: 1
#                # 令牌桶的容量，允许在一秒钟内完成的最大请求数
#                redis-rate-limiter.burstCapacity: 4
          - id: user_route   # 唯一标识符
            uri: lb://user
            predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
            filters:
            - StripPrefix=1
#        订单微服务
          - id: order_route
            uri: lb://order
            predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
            filters:
            - StripPrefix=1

  #Redis配置
#  redis:
#    host: 192.168.31.200
#    port: 6379
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
